### ISSUE TITLE
pycapa performance

### ISSUE THREAD

**Issue by zhuzhibo0** [OpenSOC/pycapa#1]
I have 100MB packets ,but it can only capture 2MB. I think this code is a demo.

**Comment by zhuzhibo0** [comment]
I rewrited this by C, then it can capture all packets and send them to kafka.

**Comment by tpiscitell** [comment]
You are correct. This tool is not meant to be performant. The README states as much:

"It is intended as a testing and development tool. It is not performant enough for production operations."

If you have re-written this in C, please feel free to share a link to your repo. At the time of commenting I did not see it on your github profile.
